### ISSUE TITLE
Off-topic - how do you constantly getting the sf SVN repository synced to here?

### ISSUE THREAD

**Issue by edwinyzh** [frones/ZeosLib#1]
ZeosLib is a great  FPC/Delphi DB access library but I'm posting an kinda offtopic question if you don't mind - how do you constantly getting the sourceforget SVN repository synced to a github repository? 

I want to keep using svn internally but also want a copy on github, how do you do that? 

I appreciate it if you can give me some instructions!

**Comment by GabrielF7** [comment]
As long as you keep the git repo read-only, you're good. If you start to make commits directly to git, the design differences between SVN and GIT become important and you may need manual work to sync back to SVN, especially if you have a team working with you.

In my case here, it's just a mirror, so I'm just using plain simple [git-svn](https://git-scm.com/docs/git-svn). I initialized the git repo specifying the correct paths to the branches and tags sub-folders, in order to get them right in git. And now I'm using this script to keep it up to date:

```
#!/bin/bash

git checkout master
git svn fetch
git svn rebase

SVNBRANCHES=$(git branch -r --list | grep 'origin/' | grep -v 'origin/tags/' | grep -v 'origin/trunk$')
SVNTAGS=$(git branch -r --list | grep 'origin/tags/')

for SVNBRANCH in $SVNBRANCHES
do
    GITBRANCH=$(echo $SVNBRANCH | sed -e '{ s/origin\/// }')
    git branch -f $GITBRANCH $SVNBRANCH
done

for SVNTAG in $SVNTAGS
do
    GITTAG=$(echo $SVNTAG | sed -e '{ s/origin\/tags\/// }')
    git tag -f $GITTAG $SVNTAG
done

git push --all h
git push --tags h
```

**Comment by edwinyzh** [comment]
Thanks for the detailed explanation @GabrielF7 ! 
Yes, I'm plan to make the github repo serves as a backup only repo (meaning it only being synced with the master svn repo)
I'm not familiar with the git commands (I'm still on a Win7 machine), but I'll try to understand all these and have a try.

**Comment by j0t4** [comment]
thanks
